services:
  app:
    build: ./
    command: bash -c "sleep 5 && make migrate-up && ./app"
    ports:
      - 8889:8889
    network_mode: host
    depends_on:
      - db
      - redis-mq
    environment:
      DATABASE_URL: ${DATABASE_URL}

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  redis-mq:
    image: redis:6.2-alpine
    ports:
      - 6379:6379