env: "local" # local, dev, prod

http_server:
  address: "localhost:8888"
  timeout: 4s
  idle_timeout: 60s
  upload_dir: "/tmp/image-converter"
  max_size: 5 # Mb

database:
  host: "localhost"
  username: "postgres"
  port: "5432"
  db_name: "postgres"
  ssl_mode: "disable"

s3server:
  endpoint: "s3.amazonaws.com"
  region: "eu-north-1"
  bucket_name: "my-bucket-webp"
  url: "http://dwah87zivx7wf.cloudfront.net" #CDN domain